### ISSUE TITLE
出版に向けた整形

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/rosbook_pkgs#32]
以下の点について修正予定です。

- [x] ブランチ整理
- [x] README の修正 

他にやるべきことがあればご指摘ください。

**Comment by MoriKen254** [comment]
chapter7, chapter9 のブランチ消しますね。9/12まで待つので、異論あれば上げてください。

**Comment by RyodoTanaka** [comment]
chapter7, chapter9 のブランチ，消してOKと思います．

**Comment by MoriKen254** [comment]
当該ブランチ削除しました。

README更新しました。

https://github.com/Nishida-Lab/rosbook_pkgs

**Comment by RyodoTanaka** [comment]
@MoriKen254 
当Issueってもう消しても大丈夫ですか？

**Comment by MoriKen254** [comment]
@RyodoTanaka 
ありがとう。そうですね、Closeします。
