### ISSUE TITLE
パッケージの命名規則について

### ISSUE THREAD

**Issue by RyodoTanaka** [Nishida-Lab/rosbook_pkgs#8]
@Nishida-Lab/ros_book 
https://github.com/AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition
上記で実施されている方法だと，
- 複数のパッケージが必要無い章ではパッケージを直接アップロード
- 複数のパッケージが必要な章では，メタパッケージを作成してアップロード

という方法が取られています．
本リポジトリでもこれに習いたいと思います．

**Comment by MoriKen254** [comment]
#24 で解決しました。閉じます。
